Improve docs for 0.3, fix #51
pietroppeter/nimibook pull request #56
Opened 2022-07-11 18:15 UTC by pietroppeter

(also testing pr deploy preview)

2022-07-11 18:25 UTC, HugoGranstrom commented
Seems like you are using the `NETLIFY_SITE_ID` from your nimib project instead of the nimibook one

2023-01-26 16:57 UTC, pietroppeter commented
not sure why this is still hanging here, my bad, will try to look a this. also #51 has a bunch of tasks I listed back then and not sure if they are covered by this (which is essentially just adding a changelog and making sure we use nimib 0.3 - which is now probably outdated already - we should use latest stable...

2023-01-26 18:35 UTC, HugoGranstrom commented
Yes it would be nice if we could get nimibook 0.3 released soon, so we can focus fully on the SSG + nimib org in the coming months. I will try and get https://github.com/pietroppeter/nimib/pull/163 done this week, so we can merge #61 as soon as possible as well. Is there anything else code-wise that has to be done, or was stabilizing the parallel build the final thing?

2023-01-26 18:39 UTC, pietroppeter commented
No, I do not recall anything code wise that needed to be done. It was mostly documenting all the changes the went through the refactoring. For the async thing at the time the idea was to disable, now there is no need to do it.

2023-01-26 18:40 UTC, pietroppeter commented
Does #61 depends on that nimib code thing?

2023-01-26 18:41 UTC, HugoGranstrom commented
Ok, that's good 👌

2023-01-26 18:43 UTC, HugoGranstrom commented
I added the parallel out.js fix to that PR 🙃 could have done it in a separate PR of course... But I just have to go through all the existing nimib documents again and confirm nothing has been broken by it. (When you have to read through all of scinim/getting-started you realize that we have quite a bit of material there 🤣)

2023-01-26 18:45 UTC, pietroppeter commented
> added the parallel out.js fix to that PR

ah ok right, you mentioned that

2023-01-26 18:51 UTC, HugoGranstrom commented
If I don't find any bugs in it, I should be able to have it done tomorrow evening. And then I should have #61 done on saturday. Just in time before the speaking hours 😎

2023-01-26 18:54 UTC, pietroppeter commented
wait the error in tests I see is due to the out.js and is the one that will be fixed?

2023-01-26 18:58 UTC, HugoGranstrom commented
Yes I think so, it's hard to tell without seeing the log file though 😛 I think we are always compiling a js file even if no nbJs is used, but I fixed that one as well in the nimib PR. Hence the error here even if we don't use nbJs

2023-01-26 19:20 UTC, pietroppeter commented
> wait the error in tests I see is due to the out.js and is the one that will be fixed?

I see that if I run multiple times `nimble genbook` I occasionally get the same error I see in CI and it seems to be tied to `out.js`. Why are we producing a js since this book has no js functionalities?

2023-01-26 19:26 UTC, HugoGranstrom commented
Because I never added a check to see if we actually wrote any nbJs code. So it just compiles an empty `.nim` file in this case for every file. As I said, I have fixed this as well in the nimib PR by checking if we have any code to compile.

2023-01-26 19:57 UTC, pietroppeter commented
anyway now I remember what this PR was about, documentation on how to use nimibook needs to be improved substantially. things changed in last refactoring and they are not documented anywhere (except in the code9

2023-01-26 20:02 UTC, HugoGranstrom commented
Oh... Yeah that's a bit more 😅 I would need to read that tutorial as well 🙊

2023-02-19 18:16 UTC, pietroppeter commented
finally this PR is ready to be merged! @HugoGranstrom do you want to give a quick look before I merge and tag 0.3 release?

I did change substantially the documentation that now reflects the current state of nimibook.
Also the changelog is now rather complete.
And I have also made some additional improvements in this PR:
- added support for nim 2.0 by removing dependency on toml_serialization (used the useful `loadTomlSection` from nimib)
- changed behaviors of some commands (clean and update)

see first PR message for all the details (I kept it up to date).

2023-02-19 19:14 UTC, HugoGranstrom requested changes
Awesome work on cleaning up and writing documentation! :smile: 

I didn't find anything major, just a few link-related comments that needs to be fixed and a very picky comment on the Latex part :)

2023-02-19 19:14 UTC, HugoGranstrom commented on book/content.nim
> +**Inline equations** are obtained with delimiters `$..$`. The following inline paragraph:
This is a bit picky, but I read this as you should write equations like `$. e{\pi i} .$`. Adding a third dot and adding spaces makes it more obvious that the points just placeholders.
```suggestion
**Inline equations** are obtained with delimiters `$ ... $`. The following inline paragraph:
```

2023-02-19 19:14 UTC, HugoGranstrom commented on book/content.nim
> +**Block equations** are obtained with delimiters `$$..$$`. The follwing block equation:
```suggestion
**Block equations** are obtained with delimiters `$$ ... $$`. The follwing block equation:
```

2023-02-19 19:59 UTC, pietroppeter commented on README.md
> +To follow up on recent changes check the [changelog.md](changelog.md).
Should be fixed now (although it currently links to a file that does not yet exists...)

2023-02-19 20:01 UTC, pietroppeter commented
Thanks! Will wait for CI to finish and merge after giving another look at the preview.

2023-02-19 20:32 UTC, merged